name: Mirror Repository

on:
  workflow_dispatch: # TODO: remove
  push:
    branches:
      - pipelines  # Change this to your source branch.

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Mirror to Target Repository
        run: |
          git remote set-url origin https://github.com/basil3366/newrep-security.git
          git push --mirror
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          echo: $GH_PAT
      - name: Mirror to GitHub Repository
        run: |
          git remote add target https://github.com/basil3366/newrep-security.git
          git push --mirror target
        env:
          GH_PAT: ${{ secrets.GH_PAT }}